# Generated by Django 4.2.4 on 2023-09-05 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_amount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='count',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
