# Generated by Django 4.2.4 on 2023-09-07 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_options_alter_recipes_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
