# Generated by Django 4.2.4 on 2023-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_favorite_options_alter_shopping_cart_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('color', 'slug', 'name'), name='unique_tags'),
        ),
    ]
